name: .NET Build & UnitTests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/**"
  pull_request:
    paths:
    - "src/**"
  
env:
  WORKING_DIRECTORY: src

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            osName: Windows
    name: Build on ${{ matrix.osName }}
    permissions:
      contents: read
    uses: MareMare/ReusableWorkflows/.github/workflows/ci.net6.yml@main
    with:
      runner-os: ${{ matrix.os }}
      working-directory: ${{ env.WORKING_DIRECTORY }}
      testing-directory: ${{ env.WORKING_DIRECTORY }}
      run-unittest: 'false'
      unittest-filter: ''
