name: .NET Build & UnitTests

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "src/**"
  pull_request:
    paths:
    - "src/**"
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: src
  TESTING_DIRECTORY: src

jobs:
  build:
    permissions:
      contents: read
    runs-on: windows-latest
    steps:
    - name: 🛒 Checkout
      uses: actions/checkout@v5
    - name: ✨ Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 🚚 Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: 🛠️ Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
